//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPlac0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AutoPlac1Entities1 : DbContext
    {
        public AutoPlac1Entities1()
            : base("name=AutoPlac1Entities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Prodata_vozila> Prodata_vozila { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ugovor> Ugovors { get; set; }
        public virtual DbSet<Vozilo> Voziloes { get; set; }
    }

    public class LocalDB : DbContext
    {
        public LocalDB()
            : base("name=DefaultConnection")
        { }

        public DbSet<AspNetUsers> Users { get; set; }
    }
}
