//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPlac0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Prodata_vozila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prodata_vozila()
        {
            this.Ugovors = new HashSet<Ugovor>();
        }
       
        
        public int IDVozila { get; set; }
        
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Godiste { get; set; }
        public int Cena { get; set; }
        public string Boja { get; set; }
        public int BrojSedista { get; set; }
        public string TipGoriva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ugovor> Ugovors { get; set; }
    }
}
