//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPlac0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ugovor
    {
        public int BrojUgovora { get; set; }
        [RegularExpression(@"((^|, )([A-z]{1,999}|[0-9]{1,999}|[A-z]{1,20}[0-9]{1,999}|[0-9]{1,999}[A-z]{1,999}))$", ErrorMessage = "Model nije tacno unesen")]
        public string Marka { get; set; }
        [RegularExpression(@"((^|, )([A-z]{1,999}|[0-9]{1,999}|[A-z]{1,20}[0-9]{1,999}|[0-9]{1,999}[A-z]{1,999}))$", ErrorMessage = "Model nije tacno unesen")]
        public string Model { get; set; }
        [RegularExpression(@"[0-9]{4}$", ErrorMessage = "Mora imati 4 karaktera.")]
        public int Godiste { get; set; }
        [RegularExpression(@"[0-9]{1,1000000}$", ErrorMessage = "Netacno uneta cena.")]
        public int Cena { get; set; }
        [RegularExpression(@"[A-z]{2,20}$", ErrorMessage = "Boja treba da ima minimum 2, a maksimum 20 slova.")]
        public string Boja { get; set; }
        [RegularExpression(@"[A-z]{2,20}$", ErrorMessage = "Ime kupca treba da ima minimum 2, a maksimum 20 slova.")]
        public string ImeKupca { get; set; }
        [RegularExpression(@"[A-z]{2,20}$", ErrorMessage = "Prezime kupca treba da ima minimum 2, a maksimum 20 slova.")]
        public string PrezimeKupca { get; set; }
        [RegularExpression(@"[A-z]{2,20}$", ErrorMessage = "Ime prodavca treba da ima minimum 2, a maksimum 20 slova.")]
        public string ImeProdavca { get; set; }
        [RegularExpression(@"[A-z]{2,20}$", ErrorMessage = "Prezime prodavca treba da ima minimum 2, a maksimum 20 slova.")]
        public string PrezimeProdavca { get; set; }
        [RegularExpression(@"[0-9]{13}$", ErrorMessage = "JMBG mora da ima 13 karaktera.")]
        public string JBMGKupca { get; set; }
        
        public int IDRadnika { get; set; }
        public int IDProdatogVozila { get; set; }
    
        public virtual Prodata_vozila Prodata_vozila { get; set; }
        public virtual Radnik Radnik { get; set; }
    }
}
