//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPlac0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vozilo
    {
       
        public int IDVozila { get; set; }
        [RegularExpression(@"((^|, )([A-z]{1,999}|[0-9]{1,20}|[A-z]{1,20}[0-9]{1,20}|[0-9]{1,20}[A-z]{1,20}))$", ErrorMessage = "Marka treba da ima minimum 2, a maksimum 20 slova.")]
        public string Marka { get; set; }
        [RegularExpression(@"((^|, )([A-z]{1,999}|[0-9]{1,20}|[A-z]{1,20}[0-9]{1,20}|[0-9]{1,20}[A-z]{1,20}))$", ErrorMessage = "Model treba da ima minimum 2, a maksimum 20 slova.")]
        public string Model { get; set; }
        [RegularExpression(@"[0-9]{4}$", ErrorMessage = "Mora imati 4 karaktera.")]
        public int Godiste { get; set; }
        [RegularExpression(@"[0-9]{1,1000000}$", ErrorMessage = "Netacno uneta cena.")]
        public int Cena { get; set; }
        [RegularExpression(@"[A-z]{2,20}$", ErrorMessage = "Boja treba da ima minimum 2, a maksimum 20 slova.")]
        public string Boja { get; set; }
        [RegularExpression(@"[0-9]{1}$", ErrorMessage = "Broj sedista treba da ima minimum 2, a maksimum 9 sedista.")]
        public int BrojSedista { get; set; }
        [RegularExpression(@"[A-z]{3,12}$", ErrorMessage = "Marka treba da ima minimum 3, a maksimum 12 slova.")]
        public string TipGoriva { get; set; }
    }
}
